### ISSUE TITLE
HIGH Revisions to verb list 

### ISSUE THREAD

**Issue by unalee** [Ripplemap/ripplemap#14]
Participated in (merge attend, assist, join. create and contribute)
Led (merge facilitate and present)
Add “Funded”
Organized (merge coordinate and manage)
Remove or hide “leave”
Can we add a way for people to add new verbs?

**Comment by dxnn** [comment]
I've changed the input form so it only shows these four verbs. There's some aliasing going on... it's complicated. But all the old data will continue working the same, this just limits the inputs. No way to add new verbs -- it requires figuring out what all the connecting words should be, so it's not as easy as just typing in a new word.
